
version: '3.4'
services:

  nginx:
    image: 'nginx:stable-alpine'
    stdin_open: true
    ports: 
      - 80:80
      - 443:443
    tty: true
    depends_on: 
      - apiauth
      - redis
      - mongodb
      - mongo-express
      - portainer
    volumes: 
      # remember!!!!!!! add trust proxy to nodejs services
      - ../app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read only 
      

  portainer:
    image: portainer/portainer-ce
    stdin_open: true
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock 
    ports: 
      - 8000:8000
      - 9000:9000

  redis:
    image: "redis:6.2.2-alpine"
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    stdin_open: true
    restart: always
    volumes:
      - redisvol:/var/lib/redis
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      # - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  # 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    stdin_open: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongovol:/data/db

  # 
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    restart: always 
    stdin_open: true  
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb

  # 
  apiauth:
    build: 
      context: ../server
      dockerfile: Dockerfile.dev
    restart: always
    stdin_open: true
    depends_on:
      - mongodb
    volumes: 
      - /app/node_modules 
      - ../server:/app
    environment:
      - PORT=5002
      - DBURL=mongodb://<MONGOUSER>:<MONGOPASS>@mongodb:27017
      - DBNAME=vanillanodemongo
      - NODE_ENV=development
      - MONGOPASS=secret
      - MONGOUSER=root
      - CORS=http://localhost:3000
      - JWT_KEY=uy6hw65hywtrnbewhnterwhg
      - JWT_TTL=365d
    ports: 
      - 5002:5002
  
volumes:
  mongovol:
    driver: local
  portainer_data:
    driver: local
  redisvol:
    driver: local